IPv4:
    docParser: "OTI_IPV4_BASE_ADD"
    register:
        0x0:
            name: "IPV4_IP_ADDR"
            type: "RW"
            desc: "ip address of offload engine"
            field: 
                31-0:
                    name: "IP_ADD"
                    rst: "0x13356219"
                    desc: "ip address of offload engine"
        
        0x4: 
            name: "IPV4_SUB_NET_MASK"
            type: "RW"
            desc: "sub net mask"
            field: 
                31-0: 
                    name: "SUBNET_MASK"
                    rst: "0XFFFFFF00"
                    desc: "sub net mask"

        0x8: 
            name: "IPV4_DEFAULT_GATEWAY"
            type: "RW"
            desc: "default gateway"    
            field: 
                31-0: 
                    name: "DFLT_GW"
                    rst: "0x0"
                    desc: "default gateway"

        0xC: 
            name: "IPV4_TX_FRAME_CNT"
            type: "RO"
            desc: "increment at each frame sent to l2"
            field: 
                31-0: 
                    name: "TX_FRAME_CNT"
                    rst: "0x0"
                    desc: "increment at each frame sent to l2"

        0x10: 
            name: "IPV4_RX_FRAME_CNT"
            type: "RO"
            desc: "increment at each frame received from l2. increment even frame contain error"
            field: 
                31-0: 
                    name: "RX_FRAME_CNT"
                    rst: "0x0"
                    desc: "increment at each frame received from l2. increment even frame contain error"
                
        0x14: 
            name: "IPV4_RX_ERROR_CHECKSUM_CNT"
            type: "RO"
            desc: "increment each time a checksum error is detected in the ipv4 header"
            field: 
                31-0: 
                    name: "RX_ERROR_CHECKSUM_CNT"
                    rst: "0x0"
                    desc: "increment each time a checksum error is detected in the ipv4 header"

        0x18: 
            name: "IPV4w_RX_ERROR_HEADER_CNT"
            type: "RO"
            desc: "increment each time the ipv4 header version not equal to 4 or hls not equal to 5 or flags not equal to 2"
            field: 
                31-0: 
                    name: "RX_ERROR_HEADER_CNT"
                    rst: "0x0"
                    desc: "increment each time the ipv4 header version not equal to 4 or hls not equal to 5 or flags not equal to 2"

        0x1C: 
            name: "IPV4_STATUS"
            type: "RO"
            desc: "ipv4 status"
            field: 
                0: 
                    name: "DFLT_GW_TABLE_ID_VALID"
                    rst: "0x0"
                    desc: "Indicate the IPv4 default gateway MAC address is resolved"
